BCRYPT_PATH = c_src

NMAKE = nmake /$(MAKEFLAGS)
CFLAGS = /O2 /EHsc /I"$(BCRYPT_PATH)"

NIF_SRC=\
	c_src\bcrypt_nif.c\
	c_src\blowfish.c

LIB_NAME = priv\bcrypt_nif.dll

all: $(LIB_NAME)

$(LIB_NAME):
	$(CC) $(CFLAGS) /I"$(ERTS_INCLUDE_PATH)" /LD /MD /Fe$@ $(NIF_SRC)
